theme: lbenicio-minimal-v1
title: Leonardo Benicio
author: Leonardo Benicio
email: hello@lbenicio.dev
description: Leonardo Benicio personal blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.lbenicio.dev" # the base hostname & protocol for your site, e.g. http://example.com
default_url: "https://lbenicio.dev" # the base hostname & protocol for your site, e.g. http://example.com
blog: "https://blog.lbenicio.dev"
twitter_username: lbenicio_
keybase_username: lbenicio_
reddit_username: lbenicio_
github_username: lbenicio
linkedin_username: leonardo-benicio-1a55a1ba

analytics:
  google: G-TZ4BSC3K2P

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  sort_field: 'date'
  sort_reverse: true
  permalink: '/page/:num/'
  title: ':title - page :num'
  pagination:
  trail: 
    before: 5
    after: 5
autopages:
  enabled: true
  categories: 
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false
    slugify:
      mode: 'default'
      case: false
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'
      case: false
  collections:
    per_page: 2
    layouts: 
      - 'autopage_collection.html'
    title: 'Feed :coll' # :coll is replaced by the collection name
    permalink: '/feed/:coll'
    silent: false
    slugify:
      mode: 'default'   # :coll is slugified.
      case: false

sass:
  sass_dir: assets
  style: compressed

# SEO
twitter:
  username: lbenicio_
  card: summary
social:
  name: Leonardo Benicio
  links:
    - https://twitter.com/lbenicio_
    - https://linkedin.com/in/leonardo-benicio-1a55a1ba
    - https://github.com/lbenicio
    - https://keybase.io/lbenicio_

logo: /_assets/img/logo.png
image: /_assets/img/logo.png

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-tagging
  - jekyll-tagging-related_posts
  - jekyll-paginate-v2
  - jekyll-minifier

# Build settings
permalink: pretty
highlighter: rouge
timezone: America/Brazil
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
svg:
  optimize: true

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/
  - _config.yml
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - benchmark
  - .ruby-version
  - CHANGELOG.md
  - rubocop/
  - .rubocop.yml
