name: Unit Tests
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: 2.7
      - name: Install Dependencies
        env:
          RAILS_ENV: test
          JEKYLL_ENV: test
        run: |
          sudo apt-get update
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build Jekyll
        env:
          RAILS_ENV: test
          JEKYLL_ENV: test
        run: bundle exec jekyll build
      - name: Testsuite
        env:
          RAILS_ENV: test
          JEKYLL_ENV: test
        run: bundle exec rake test
      - name: Results
        run: echo "🍏 This job's status is ${{ job.status }}."
